trigger:
- main

pool:
  name: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- powershell: |
    git config user.name "buildagent"
    git config user.email "build@local"

    Add-Content test.txt "hello"

    git add .
    git commit -m "pipeline commit"

    git push origin HEAD:main
  displayName: Commit and Push
